### ISSUE TITLE
Collision on slug change request

### ISSUE THREAD

**Issue by mzganec** [genialis/resolwe-bio-py#136]
Slug change request
```
obj.slug = 'taken-slug'
obj.save()
```
where `'taken-slug'` is a slug of another existing object, results in changing the slug of `obj` to `'taken-slug-N'` where `N` is a number **without any notification**.

This is dangerous for two reasons:
(1) a change to `taken-slug-N` was not requested and should therefore fail. Consider adding `force` or similar boolean argument to the `save()` function to control this behavior.
(2) someone may rely on changing the slug to `'taken-slug'` without an error and later re-accessing this object by `get('taken-slug')` which would return the wrong object.

**Comment by dblenkus** [comment]
Fixed in https://github.com/genialis/resolwe/pull/412
