### ISSUE TITLE
Make help(res.<resource>.filter) point to the list of available fields

### ISSUE THREAD

**Issue by tristanbrown** [genialis/resolwe-bio-py#138]
For example, if res is a Resolwe instance, currently, `help(res.sample.filter)` returns only:
```
filter(**filters) method of resdk.query.ResolweQuery instance
    Return clone of current query with added given filters.
```

It would be helpful if it showed the list of possible filtering fields for the sample resource that is given [here](http://resdk.readthedocs.io/en/stable/ref.html#resdk.ResolweQuery).

**Comment by mstajdohar** [comment]
Also, we should review if the filters documentation in reference in up to date. @dblenkus
