### ISSUE TITLE
Filter by contributor username, first name, and last name not possible

### ISSUE THREAD

**Issue by tristanbrown** [genialis/resolwe-bio-py#143]
Currently, `res.<resource>.filter(contributor=<id#>)` is the only way to filter by contributor. Trying to use the user's username, first name, or last name instead of ID # fails to return any objects.

**Comment by dblenkus** [comment]
This is a known limitation. It would be nice to support usage of `User` object in such cases. But this hasn't been planed yet.

**Comment by mstajdohar** [comment]
The workaround is to get the user id first:
```
res.<resource>.filter(contributor=res.user.get(username='jkokosar').id)
```

**Comment by mstajdohar** [comment]
@dblenkus It would be nice to at least support the `__in` filter, so that we could do:
```
res.data.filter(contributor__in=[user.id for user in res.user.filter(email='janez@genialis')])
```

Note that Janez has multiple test users with the same email.

**Comment by dblenkus** [comment]
> It would be nice to at least support the `__in` filter

This needs to be supported in Resolwe.
