### ISSUE TITLE
Filter by process_name returns everything

### ISSUE THREAD

**Issue by tristanbrown** [genialis/resolwe-bio-py#145]
Reproduce:
`res.data.filter(process_name='Bowtie 1.0.0', limit=3)` returns the same objects as `res.data.filter(process_name='foo', limit=3)`.

**Comment by dblenkus** [comment]
It is not supported: https://github.com/genialis/resolwe-bio-py/blob/master/resdk/query.py#L89

**Comment by JureZmrzlikar** [comment]
This should work now.
