### ISSUE TITLE
CollectionTables returns expressions and metadata with different order of samples

### ISSUE THREAD

**Issue by mzganec** [genialis/resolwe-bio-py#250]
Indices of `ct.exp` and `ct.meta`, where `ct` is a `resdk.collection_tables.CollectionTables` object, are in general not the same. The problem occurs when expressions and the associated response, which is typically stored in the metadata, are used as input in a `sklearn` estimator. Unfortunately, the `fit` method ignores the index of `pandas.DataFrame` and `pandas.Series` objects and matches expression profiles with response data by integer index and not by sample name. Thus, if the order of samples in `ct.exp` and `ct.meta` is different, reshuffled (wrong) responses may be assigned to the samples.

@robertcv proposed a solution that computes the intersection of expression and metadata indices and returns both `pandas.DataFrame`s with the same order of rows, removing samples with no expression data objects.

The current workaround is to sort expressions and metadata by their sample index in each script after obtaining them from the server.

**Comment by robertcv** [comment]
We actually already enforce that there is always just exactly one (not zero, not more) expression `Data` objects for every `Sample` object. To ensure order consistency between `ct.exp` and `ct.meta` we actually just need a consistent index order which we get by sorting it.
