### ISSUE TITLE
Table.meta not working with the latest upload-metadata processes

### ISSUE THREAD

**Issue by AGregorc** [genialis/resolwe-bio-py#284]
Since the Sample ID/slug/name naming remove the orange type `mS#...` in the new processes, `Table.meta` doesn't work anymore. 
The problem lies from this [line onward](https://github.com/genialis/resolwe-bio-py/blob/master/src/resdk/tables/base.py#L405). 

Example to reproduce error:
```python
slug = <any_new_collection_with_new_metadata_process>

res = resdk.Resolwe(url="https://app.genialis.com/")
table = RNATables(res.collection.get(slug))
table.meta
```

**Comment by JureZmrzlikar** [comment]
Fixed by #285
