### ISSUE TITLE
Helper functions for mapping gene IDs

### ISSUE THREAD

**Issue by mstajdohar** [genialis/resolwe-bio-py#69]
Details in [spec](https://docs.google.com/document/d/1KOQjP1AoAXWb0MeVaL1Ss8-eAGyG9Ys-Wg6PrfBmuoU/edit#).

Write utility functions in resdk to facilitate the interaction with knowledge base backend. Each function should do no more than a single request to the knowledge base backend, improve the backend if necessary.

* A function that maps NCBI to MGI/Uniprot using a mapping table. Inputs should be: source_db, target_db and a list of feature_ids. Output is a list of mapped/converted feature_ids 
* A function that for a list of given features returns a dictionary of values from the gene info table. Inputs: source, a list of features and an optional parameter to limit which fields are returned (see gene info table/model for a list of valid options). Output is a dict {‘feature_id’: {‘source’: ‘NCBI, ‘organism’: ‘Homo sapiens’, … }}. Key ‘feature_id’ will always be unique since all the returned elements have the same source.

**Comment by jkokosar** [comment]
@kostko When will you be able to continue work on this task? Other tasks (for the next milestone) are dependant on this.

**Comment by kostko** [comment]
The backend part has already been done (and is merged), I only need to add support to the SDK. I will try to do this today.

**Comment by kostko** [comment]
Done, see #72 for usage example. Note that this requires an update to be deployed to the backend first.

**Comment by dblenkus** [comment]
@kostko can we close this?
