### ISSUE TITLE
Error reporting 

### ISSUE THREAD

**Issue by mstajdohar** [genialis/resolwe-bio-py#70]
Catch fail at process register stage (e.g. process type = basic:file) - this fails but should be reported
with the error msg “failed to register process: bad sytnax" instead of just "error 400"

**Comment by mstajdohar** [comment]
@dblenkus What is the status of this?

**Comment by dblenkus** [comment]
Error handling was implemented quite a while ago. Now each error should be examined individually, make sure that API returns some meaningful and interpret it in the SDK. I think that each error should be treated when it occurs and is reported.
